// <auto-generated />
using System;
using IoTPetFeederDataManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IoTPetFeederDataManager.Migrations
{
    [DbContext(typeof(IoTPetFeederDbContext))]
    partial class IoTPetFeederDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("IoTPetFeederDataManager.Models.Feeder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FeedTimes")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeederId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfFeedTimes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feeders");
                });

            modelBuilder.Entity("IoTPetFeederDataManager.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IoTPetFeederDataManager.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IoTPetFeederDataManager.Models.Feeder", b =>
                {
                    b.HasOne("IoTPetFeederDataManager.Models.User", null)
                        .WithMany("Feeders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IoTPetFeederDataManager.Models.User", b =>
                {
                    b.HasOne("IoTPetFeederDataManager.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
